[2023-06-30 16:19:38] [WARNING]: Protocol -> device lock is disable. http api may fail. 
[2023-06-30 16:19:46] [ERROR]: Protocol -> test long message server latency error: failed to connect to server during quality test: dial tcp 109.244.158.52:443: i/o timeout 
[2023-06-30 16:19:46] [ERROR]: 错误: 长消息服务器延迟测试失败, 可能导致无法接收/发送长消息的情况, 请检查本地网络状态. 如果您使用的腾讯云服务器, 请修改DNS到114.114.114.114 
[2023-06-30 16:19:47] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 16:19:51] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 16:19:54] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 16:19:58] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113185,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":30,"packet_sent":21,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 16:20:00] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 16:20:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 16:20:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 16:20:10] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113198,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":30,"packet_sent":21,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 16:20:12] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 16:20:16] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 16:20:20] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 16:20:23] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113210,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":31,"packet_sent":22,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 16:20:25] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 16:20:29] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 16:20:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 16:20:36] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113223,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":31,"packet_sent":22,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 16:20:38] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 16:20:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 16:20:45] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 16:20:48] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113236,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":31,"packet_sent":22,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 16:20:50] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 16:20:54] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 16:20:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 16:21:01] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113248,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":32,"packet_sent":23,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 16:21:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 16:21:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 16:21:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 16:21:14] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113261,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":32,"packet_sent":23,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 16:21:16] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 16:21:19] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 16:21:23] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 16:21:26] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113274,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":33,"packet_sent":24,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 16:22:42] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 16:22:46] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 16:22:49] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 16:22:53] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113360,"self_id":2470751924,"interval":5000,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":46,"packet_sent":33,"packet_lost":0,"message_received":2,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113328}}}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 16:22:55] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 16:22:58] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 16:23:02] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 16:23:05] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113373,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":46,"packet_sent":33,"packet_lost":0,"message_received":2,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113328}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 16:23:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 16:23:11] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 16:23:15] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 16:23:18] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113385,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":46,"packet_sent":33,"packet_lost":0,"message_received":2,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113328}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 16:23:20] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 16:23:24] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 16:23:27] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 16:23:31] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113398,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":48,"packet_sent":35,"packet_lost":0,"message_received":2,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113328}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 16:23:33] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 16:23:36] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 16:23:40] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 16:23:43] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113411,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":48,"packet_sent":35,"packet_lost":0,"message_received":2,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113328}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 16:23:44] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:23:46] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:23:47] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:23:49] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113423,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":49,"packet_sent":36,"packet_lost":0,"message_received":2,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113328}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:23:49] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:23:50] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:23:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:23:53] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113429,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":49,"packet_sent":36,"packet_lost":0,"message_received":2,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113328}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:23:53] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:23:55] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:23:56] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:23:58] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113433,"self_id":2470751924,"interval":5000,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":49,"packet_sent":36,"packet_lost":0,"message_received":2,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113328}}}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:23:58] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:23:59] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:24:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:24:02] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:03] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113438,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":49,"packet_sent":36,"packet_lost":0,"message_received":2,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113328}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:24:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:24:04] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:24:04] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:05] [WARNING]: 上报 Event 数据 {"post_type":"message","message_type":"group","time":1688113441,"self_id":2470751924,"sub_type":"normal","font":0,"group_id":734894275,"message":"[CQ:at,qq=2470751924] weekchart 24885","sender":{"age":0,"area":"","card":"","level":"","nickname":"LemonQu","role":"member","sex":"unknown","title":"","user_id":173887664},"message_id":1182118714,"anonymous":null,"message_seq":6729,"raw_message":"[CQ:at,qq=2470751924] weekchart 24885","user_id":173887664}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:24:06] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:24:07] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113443,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":50,"packet_sent":36,"packet_lost":0,"message_received":3,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113441}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:24:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:24:09] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:24:12] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113447,"self_id":2470751924,"interval":5000,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":50,"packet_sent":36,"packet_lost":0,"message_received":3,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113441}}}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:24:12] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:24:13] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:15] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:24:16] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113452,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":51,"packet_sent":37,"packet_lost":0,"message_received":3,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113441}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:24:16] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:24:18] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:19] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:24:21] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113456,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":51,"packet_sent":37,"packet_lost":0,"message_received":3,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113441}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:24:21] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:24:22] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:24] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:24:25] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113461,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":51,"packet_sent":37,"packet_lost":0,"message_received":3,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113441}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:24:25] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:24:27] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:28] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:24:30] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113465,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":51,"packet_sent":37,"packet_lost":0,"message_received":3,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113441}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:24:30] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:24:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:33] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:24:35] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113470,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":51,"packet_sent":37,"packet_lost":0,"message_received":3,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113441}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:24:35] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:24:37] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:38] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:24:40] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113475,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":51,"packet_sent":37,"packet_lost":0,"message_received":3,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113441}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:24:40] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:24:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:24:42] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:42] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:43] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:24:44] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:24:45] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113480,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":52,"packet_sent":38,"packet_lost":0,"message_received":3,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113441}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:24:45] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:24:45] [WARNING]: 上报 Event 数据 {"post_type":"message","message_type":"group","time":1688113481,"self_id":2470751924,"sub_type":"normal","anonymous":null,"font":0,"group_id":734894275,"raw_message":"[CQ:at,qq=2470751924] fuck u","sender":{"age":0,"area":"","card":"","level":"","nickname":"LemonQu","role":"member","sex":"unknown","title":"","user_id":173887664},"user_id":173887664,"message":"[CQ:at,qq=2470751924] fuck u","message_seq":6730,"message_id":649214687}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:24:47] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:48] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:24:50] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113485,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":53,"packet_sent":38,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:24:50] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:24:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:53] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:24:55] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113490,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":53,"packet_sent":38,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:24:55] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:24:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:24:58] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:25:00] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113495,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":53,"packet_sent":38,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:25:00] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:25:02] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:25:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:25:05] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113500,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":53,"packet_sent":38,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:25:05] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:25:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:25:08] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:25:10] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113505,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":53,"packet_sent":38,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:25:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:25:12] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:25:13] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:25:15] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113510,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":54,"packet_sent":39,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:25:15] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:25:17] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:25:18] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:25:20] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113515,"self_id":2470751924,"interval":5000,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":54,"packet_sent":39,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}}}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:25:20] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:25:22] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:25:23] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:25:25] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113520,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":54,"packet_sent":39,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:25:25] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:25:27] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:25:28] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:25:30] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113525,"self_id":2470751924,"interval":5000,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":54,"packet_sent":39,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}}}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:25:30] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:25:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:25:33] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:25:35] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113530,"self_id":2470751924,"interval":5000,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":54,"packet_sent":39,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}}}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:25:35] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:25:37] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:25:38] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:25:40] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113535,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":54,"packet_sent":39,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:25:40] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:25:42] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:25:43] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:25:45] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113540,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":55,"packet_sent":40,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:25:45] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:25:47] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:25:48] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:25:50] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113545,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":55,"packet_sent":40,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:25:50] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:25:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:25:53] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:25:55] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113550,"self_id":2470751924,"interval":5000,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":55,"packet_sent":40,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}}}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:25:55] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:25:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:25:58] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:26:00] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113555,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":55,"packet_sent":40,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:26:00] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:26:02] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": read tcp 127.0.0.1:50213->127.0.0.1:5701: wsarecv: An existing connection was forcibly closed by the remote host. 将进行第 2 次重试 
[2023-06-30 16:26:04] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:26:06] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113560,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":55,"packet_sent":40,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:26:06] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:26:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:26:09] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:26:10] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113566,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":55,"packet_sent":40,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:26:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:26:12] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 16:26:13] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 3 次重试 
[2023-06-30 16:26:15] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688113570,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":56,"packet_sent":41,"packet_lost":0,"message_received":4,"message_sent":2,"disconnect_times":0,"lost_times":0,"last_message_time":1688113481}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 停止上报：已达重试上限 
[2023-06-30 16:26:15] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 1 次重试 
[2023-06-30 16:26:17] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": net/http: HTTP/1.x transport connection broken: unexpected EOF 将进行第 2 次重试 
[2023-06-30 20:39:47] [WARNING]: Protocol -> device lock is disable. http api may fail. 
[2023-06-30 20:39:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 20:40:00] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 20:41:02] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 20:41:05] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 20:41:09] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 20:41:12] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688128860,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":37,"packet_sent":24,"packet_lost":0,"message_received":3,"message_sent":1,"disconnect_times":0,"lost_times":0,"last_message_time":1688128850}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 20:41:14] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 20:41:18] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 20:41:21] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 20:41:25] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688128872,"self_id":2470751924,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":37,"packet_sent":24,"packet_lost":0,"message_received":3,"message_sent":1,"disconnect_times":0,"lost_times":0,"last_message_time":1688128850}},"interval":5000}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 20:41:27] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 20:41:31] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 20:41:34] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 20:41:38] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688128885,"self_id":2470751924,"interval":5000,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":38,"packet_sent":25,"packet_lost":0,"message_received":3,"message_sent":1,"disconnect_times":0,"lost_times":0,"last_message_time":1688128850}}}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 20:41:40] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 20:41:43] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 20:41:47] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-06-30 20:41:50] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1688128898,"self_id":2470751924,"interval":5000,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":38,"packet_sent":25,"packet_lost":0,"message_received":3,"message_sent":1,"disconnect_times":0,"lost_times":0,"last_message_time":1688128850}}}
 到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-06-30 20:41:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-06-30 20:41:56] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-06-30 20:42:00] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
